"""
Django settings for HvM project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
from dotenv import load_dotenv
import os

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-st^bq&sdzt9!&f%ph#1fps5!#@^_kx)b$d$y+ap)!s&_8yx8ni",
)

DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"

# Pour dev local
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# -----------------------------------
# Applications
# -----------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Ajouts
    "rest_framework",
    "corsheaders",
    "channels",

    "game.apps.GameConfig",
    "payments",
]

# -----------------------------------
# Middleware
# -----------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # CORS doit être haut
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",

    # CSRF doit être actif pour SessionAuthentication
    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "HvM.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "HvM.wsgi.application"

# -----------------------------------
# Channels
# -----------------------------------
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# -----------------------------------
# Database (dev sqlite)
# -----------------------------------
""" DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
} """

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'hvm_db',
        'USER': 'postgres',
        'PASSWORD': '123456789',
        'HOST': 'localhost',  # ou IP du serveur
        'PORT': '5432',       # port par défaut
    }
}

# -----------------------------------
# Auth / User model
# -----------------------------------
AUTH_USER_MODEL = "game.User"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------------
# i18n
# -----------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -----------------------------------
# Static
# -----------------------------------
STATIC_URL = "static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =========================================================
# ✅ DRF: SessionAuthentication (cookies) + CSRF
# =========================================================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# =========================================================
# ✅ CORS / CSRF pour Next.js -> Django avec cookies
# =========================================================
FRONTEND_ORIGIN = os.getenv("FRONTEND_ORIGIN", "http://localhost:3000")

# ❌ Ne pas utiliser CORS_ALLOW_ALL_ORIGINS avec credentials/cookies
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    FRONTEND_ORIGIN,
    "http://localhost:3000",
]

# ✅ Obligatoire pour envoyer/recevoir sessionid + csrftoken
CORS_ALLOW_CREDENTIALS = True

# Autoriser l'origine front pour CSRF
CSRF_TRUSTED_ORIGINS = [
    FRONTEND_ORIGIN,
]

# Cookies (DEV: HTTP)
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Dev local: Lax OK (cookies envoyés sur navigation + fetch same-site-ish)
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Optionnel mais utile en dev
CSRF_COOKIE_HTTPONLY = False  # laisser JS lire csrftoken (pour X-CSRFToken)

# =========================================================
# (Optionnel) Sécurité base en dev
# =========================================================
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
ASGI_APPLICATION = "HvM.asgi.application"
