# Generated by Django 5.2.8 on 2026-01-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_feedback'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['user', 'created_at'], name='game_game_user_id_5b5cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'created_at'], name='game_game_status_9bfe99_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['result', 'created_at'], name='game_game_result_faa688_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['mode', 'created_at'], name='game_game_mode_6eea58_idx'),
        ),
    ]
