# Generated by Django 5.2.8 on 2026-01-24 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_game_game_user_id_5b5cc1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_ranked', models.IntegerField(default=1200)),
                ('games_ranked', models.IntegerField(default=0)),
                ('wins_ranked', models.IntegerField(default=0)),
                ('losses_ranked', models.IntegerField(default=0)),
                ('draws_ranked', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PvPGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('casual', 'Casual'), ('ranked', 'Ranked')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
                ('result', models.CharField(choices=[('ongoing', 'Ongoing'), ('x_win', 'X win'), ('o_win', 'O win'), ('draw', 'Draw')], default='ongoing', max_length=16)),
                ('board_size', models.IntegerField(default=15)),
                ('turn', models.CharField(default='X', max_length=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_move_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('turn_timeout_sec', models.IntegerField(default=30)),
                ('time_control', models.JSONField(blank=True, null=True)),
                ('player_o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_games_as_o', to=settings.AUTH_USER_MODEL)),
                ('player_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_games_as_x', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('casual', 'Casual'), ('ranked', 'Ranked')], max_length=16)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('matched', 'Matched'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='waiting', max_length=16)),
                ('elo_snapshot', models.IntegerField(default=1200)),
                ('preferences', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['mode', 'status', 'created_at'], name='game_matchq_mode_bf63c1_idx'), models.Index(fields=['mode', 'status', 'elo_snapshot'], name='game_matchq_mode_e3a0b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PvPMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('player', models.CharField(max_length=1)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.pvpgame')),
            ],
            options={
                'indexes': [models.Index(fields=['game', 'move_number'], name='game_pvpmov_game_id_1ca951_idx'), models.Index(fields=['game', 'row', 'col'], name='game_pvpmov_game_id_ec86d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('game', 'row', 'col'), name='uniq_pvp_game_cell'), models.UniqueConstraint(fields=('game', 'move_number'), name='uniq_pvp_game_move_number')],
            },
        ),
    ]
