# Generated by Django 5.2.8 on 2026-01-27 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_playerrating_pvpgame_matchqueueentry_pvpmove'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchqueueentry',
            name='matched_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.pvpgame'),
        ),
    ]
