# Generated by Django 5.2.8 on 2026-02-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_pvp_invite_used_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rematchrequest',
            new_name='game_rematc_game_id_33dca5_idx',
            old_name='game_rematch_game_id_3e15cd_idx',
        ),
    ]
