# Generated by Django 5.2.8 on 2026-02-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_pvpgame_schema_alignment'),
        ('game', '0010_rename_game_rematch_game_id_3e15cd_idx_game_rematc_game_id_33dca5_idx'),
    ]

    operations = [
    ]
